Repository FRI-DAY/sonar-gosu-plugin, pull requests merged in 2023-07, with the labels that each got.

#93 tech-debit: enable SonarCloud analysis on PRs from forks repositories
  .github/workflows/build.yml
  .github/workflows/release.yml
  .github/workflows/sonar.yml
Labels: tech-debt

#97 bug-fix: UnnecessaryImportRule avoids trying to map class names of wildcard imports
  build.gradle
  src/main/java/de/friday/sonarqube/gosu/language/statements/UsesStatement.java
  src/main/java/de/friday/sonarqube/gosu/plugin/rules/smells/UnnecessaryImportRule.java
  src/test/java/de/friday/sonarqube/gosu/language/statements/UsesStatementTest.java
  src/test/java/de/friday/sonarqube/gosu/plugin/rules/smells/UnnecessaryImportRuleTest.java
  src/test/resources/rules/UnnecessaryImportRule/nok.gs
  src/test/resources/rules/UnnecessaryImportRule/ok.gs
  src/testIntegration/java/de/friday/sonarqube/gosu/plugin/SimpleGosuProjectIT.java
  src/testIntegration/resources/projects/simple-gosu-project/src/main/gosu/de/friday/gosu/simple/FizzBuzz.gs
Labels: bug

#88 feat: enable UnnecessaryImportRule to exclude specific import namespace from analysis
  src/main/java/de/friday/sonarqube/gosu/plugin/rules/smells/UnnecessaryImportRule.java
  src/test/java/de/friday/sonarqube/gosu/plugin/rules/smells/UnnecessaryImportRuleTest.java
  src/test/resources/rules/UnnecessaryImportRule/nok.gs
Labels: enhancement

#87 bug-fix: UnnecessaryImportRule highlights unused import on its line
  src/main/java/de/friday/sonarqube/gosu/plugin/rules/smells/UnnecessaryImportRule.java
  src/test/java/de/friday/sonarqube/gosu/plugin/rules/smells/UnnecessaryImportRuleTest.java
  src/test/resources/rules/UnnecessaryImportRule/nokUnusedImport.gs
Labels: bug
